name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      run-build:
        description: 'Whether to run the build step'
        required: false
        default: false
        type: boolean
    secrets:
      # Add any secrets if needed in the future

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint:check
      
    - name: Run tests
      run: npm test
      
    - name: Build project
      if: inputs.run-build
      run: npm run build
      
    - name: Check build output
      if: inputs.run-build
      run: |
        if [ -d "dist" ]; then
          echo "✅ Build successful - dist directory exists"
          ls -la dist/
        else
          echo "❌ Build failed - dist directory not found"
          exit 1
        fi 