name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build-and-test:
    uses: ./.github/workflows/base.yml
    with:
      run-build: true 