name: Run Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    uses: ./.github/workflows/base.yml
    with:
      run-build: false 